import React from 'react';
import GenericFilter from '../../common/GenericFilter';

const FiltroEscuelas = ({ filtroInicial }) => {
  const configuracionFiltro = [
    {   'clave': 'tipo_reg',
    'etiqueta': 'Tipo Reg',
    'placeholder': 'Tipo Reg',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'codigo_liquidacion',
    'etiqueta': 'Codigo Liquidación',
    'placeholder': 'Codigo Liquidación',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'centro_pago',
    'etiqueta': 'Centro Pago',
    'placeholder': 'Centro Pago',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'pago_anio',
    'etiqueta': 'Pago Anio',
    'placeholder': 'Pago Anio',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'pago_mes',
    'etiqueta': 'Pago Mes',
    'placeholder': 'Pago Mes',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'pago_dia',
    'etiqueta': 'Pago Dia',
    'placeholder': 'Pago Dia',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'suc_acreditacion',
    'etiqueta': 'Suc Acreditacion',
    'placeholder': 'Suc Acreditacion',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'importe_acreditado',
    'etiqueta': 'Importe Acreditado',
    'placeholder': 'Importe Acreditado',
    'tipo': 'float',
    'valor': ''},
    {   'clave': 'beneficiario_nombre',
    'etiqueta': 'Apellido Nombre',
    'placeholder': 'Apellido Nombre',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'documento_nro',
    'etiqueta': 'Nro Documento',
    'placeholder': 'Nro Documento',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'cuenta_debito',
    'etiqueta': 'Cuenta Debito',
    'placeholder': 'Cuenta Debito',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'cuil',
    'etiqueta': 'Cuil',
    'placeholder': 'Cuil',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'zona',
    'etiqueta': 'Zona',
    'placeholder': 'Zona',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'centro',
    'etiqueta': 'Centro',
    'placeholder': 'Centro',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'sector',
    'etiqueta': 'Sector',
    'placeholder': 'Sector',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'padron',
    'etiqueta': 'Padron',
    'placeholder': 'Padron',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'cod_banco',
    'etiqueta': 'Codigo Banco',
    'placeholder': 'Codigo Banco',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'fuente',
    'etiqueta': 'Fuente',
    'placeholder': 'Fuente',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'reservado',
    'etiqueta': 'Reservado',
    'placeholder': 'Reservado',
    'tipo': 'str',
    'valor': ''},
];
  
  return (
    <GenericFilter
      configuracion={configuracionFiltro}
      filtroInicial={filtroInicial}
    />
  );
};

export default FiltroEscuelas;
