import React from 'react';
import GenericFilter from '../../common/GenericFilter';

const FiltroEscuelas = ({ filtroInicial }) => {
  const configuracionFiltro = [
    // {   'clave': 'tipo_reg',
    // 'etiqueta': 'Tipo Reg',
    // 'placeholder': 'Tipo Reg',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cod_liquidacion',
    // 'etiqueta': 'Código Liquidación',
    // 'placeholder': 'Código Liquidación',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'centro_pago',
    // 'etiqueta': 'Centro Pago',
    // 'placeholder': 'Centro Pago',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'pago_anio',
    // 'etiqueta': 'Año Pago',
    // 'placeholder': 'Año Pago',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'pago_mes',
    // 'etiqueta': 'Mes Pago',
    // 'placeholder': 'Mes Pago',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'pago_dia',
    // 'etiqueta': 'Día Pago',
    // 'placeholder': 'Día Pago',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'suc_acreditacion',
    // 'etiqueta': 'Sucursal Acreditación',
    // 'placeholder': 'Sucursal Acreditación',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'tipo_acreditacion',
    // 'etiqueta': 'Tipo Acreditación',
    // 'placeholder': 'Tipo Acreditación',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cuenta_acreditacion',
    // 'etiqueta': 'Cuenta Acreditación',
    // 'placeholder': 'Cuenta Acreditación',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cuenta_acreditacion_dv',
    // 'etiqueta': 'DV Cuenta Acreditación',
    // 'placeholder': 'DV Cuenta Acreditación',
    // 'tipo': 'str',
    // 'valor': ''},
    // TODO: si activo importe_acreditado, da un problema y es que al tener 0 al a izquierda, los elimina, haciendo que no coincida el numero con el que se guardo en la base de datos. Pero viendo el tipo de dato en la DB, es str, no float
    // {   'clave': 'importe_acreditado',
    // 'etiqueta': 'Importe Acreditado',
    // 'placeholder': 'Importe Acreditado',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'beneficiario_nombre',
    // 'etiqueta': 'Beneficiario',
    // 'placeholder': 'Beneficiario',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'documento_tipo',
    // 'etiqueta': 'Tipo Documento',
    // 'placeholder': 'Tipo Documento',
    // 'tipo': 'str',
    // 'valor': ''},
    {   'clave': 'documento_nro',
    'etiqueta': 'Número Documento',
    'placeholder': 'Número Documento',
    'tipo': 'str',
    'valor': ''},
    // {   'clave': 'suc_debito',
    // 'etiqueta': 'Sucursal Débito',
    // 'placeholder': 'Sucursal Débito',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'tipo_debito',
    // 'etiqueta': 'Tipo Débito',
    // 'placeholder': 'Tipo Débito',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cuenta_debito',
    // 'etiqueta': 'Cuenta Débito',
    // 'placeholder': 'Cuenta Débito',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cuenta_debito_dv',
    // 'etiqueta': 'DV Cuenta Débito',
    // 'placeholder': 'DV Cuenta Débito',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cuil',
    // 'etiqueta': 'CUIL',
    // 'placeholder': 'CUIL',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'zona',
    // 'etiqueta': 'Zona',
    // 'placeholder': 'Zona',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'centro',
    // 'etiqueta': 'Centro',
    // 'placeholder': 'Centro',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'sector',
    // 'etiqueta': 'Sector',
    // 'placeholder': 'Sector',
    // 'tipo': 'str',
    // 'valor': ''},
    {   'clave': 'padron',
    'etiqueta': 'Padrón',
    'placeholder': 'Padrón',
    'tipo': 'str',
    'valor': ''},
    // {   'clave': 'padron_dv',
    // 'etiqueta': 'DV Padrón',
    // 'placeholder': 'DV Padrón',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'reservado',
    // 'etiqueta': 'Reservado',
    // 'placeholder': 'Reservado',
    // 'tipo': 'str',
    // 'valor': ''},
    // {   'clave': 'cod_banco',
    // 'etiqueta': 'Código Banco',
    // 'placeholder': 'Código Banco',
    // 'tipo': 'str',
    // 'valor': ''},
    {   'clave': 'tipo_archivo',
    'etiqueta': 'Tipo Archivo',
    'placeholder': 'Tipo Archivo',
    'tipo': 'str',
    'valor': ''},
    // {   'clave': 'periodo',
    // 'etiqueta': 'Período',
    // 'placeholder': 'Período',
    // 'tipo': 'str',
    // 'valor': ''},
    {   'clave': 'motivo',
    'etiqueta': 'Motivo',
    'placeholder': 'Motivo',
    'tipo': 'select',
    'valor': ''},
    {   'clave': 'bloqueo',
    'etiqueta': 'Bloqueo',
    'placeholder': 'Bloqueo',
    'tipo': 'checkbox',
    'valor': ''},
    // {   'clave': 'activo',
    // 'etiqueta': 'Activo',
    // 'placeholder': 'Activo',
    // 'tipo': 'checkbox',
    // 'valor': ''},

];
  
  return (
    <GenericFilter
      configuracion={configuracionFiltro}
      filtroInicial={filtroInicial}
    />
  );
};

export default FiltroEscuelas;
