import React from 'react';
import GenericFilter from '../../common/GenericFilter';

const FiltroEscuelas = ({ filtroInicial }) => {
  const configuracionFiltro = [
    {   'clave': 'bloqueo',
    'etiqueta': 'Bloqueo',
    'placeholder': 'Bloqueo',
    'tipo': 'checkbox',
    'valor': ''},
    {   'clave': 'tipo_reg',
    'etiqueta': 'Tipo Reg',
    'placeholder': 'Tipo Reg',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'codigo_liquidacion',
    'etiqueta': 'Codigo Liquidación',
    'placeholder': 'Codigo Liquidación',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'centro_pago',
    'etiqueta': 'Centro Pago',
    'placeholder': 'Centro Pago',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'fecha_pago',
    'etiqueta': 'Fecha Pago',
    'placeholder': 'Fecha Pago',
    'tipo': 'datetime',
    'valor': ''},
    {   'clave': 'sucursal_acreditacion',
    'etiqueta': 'Suc Acreditacion',
    'placeholder': 'Suc Acreditacion',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'importe_acreditar',
    'etiqueta': 'Importe Acreditar',
    'placeholder': 'Importe Acreditar',
    'tipo': 'float',
    'valor': ''},
    {   'clave': 'ayn',
    'etiqueta': 'Apellido Nombre',
    'placeholder': 'Apellido Nombre',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'tipoynumdoc',
    'etiqueta': 'Tipo  y Numero Doc',
    'placeholder': 'Tipo  y Numero Doc',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'sucursal_cuenta_digitodebito',
    'etiqueta': 'Suc Cuenta Digito Debito',
    'placeholder': 'Suc Cuenta Digito Debito',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'cuil',
    'etiqueta': 'Cuil',
    'placeholder': 'Cuil',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'zona',
    'etiqueta': 'Zona',
    'placeholder': 'Zona',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'centro_sector',
    'etiqueta': 'Centro Sector',
    'placeholder': 'Centro Sector',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'padron_digitoverificador',
    'etiqueta': 'Padron',
    'placeholder': 'Padron',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'codigo_banco',
    'etiqueta': 'Codigo Banco',
    'placeholder': 'Codigo Banco',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'motivo',
    'etiqueta': 'Motivo',
    'placeholder': 'Motivo',
    'tipo': 'select',
    'valor': ''},
    {   'clave': 'fuente',
    'etiqueta': 'Fuente',
    'placeholder': 'Fuente',
    'tipo': 'str',
    'valor': ''},
    {   'clave': 'activo',
    'etiqueta': 'Activo',
    'placeholder': 'Activo',
    'tipo': 'checkbox',
    'valor': ''},
];
  
  return (
    <GenericFilter
      configuracion={configuracionFiltro}
      filtroInicial={filtroInicial}
    />
  );
};

export default FiltroEscuelas;
