export const formularioCampos = [
  {name: "bloqueo", label: "Bloqueo", placeholder: "Bloqueo", type: "checkbox"},
  {name: "tipo_reg", label: "Tipo Reg", placeholder: "no_visible", type: "text"},
  {name: "cod_liquidacion", label: "Código Liquidación", placeholder: "no_visible", type: "text"},
  {name: "centro_pago", label: "Centro Pago", placeholder: "Centro Pago", type: "text"},
  {name: "pago_anio", label: "Año Pago", placeholder: "no_visible", type: "text"},
  {name: "pago_mes", label: "Mes Pago", placeholder: "no_visible", type: "text"},
  {name: "pago_dia", label: "Día Pago", placeholder: "no_visible", type: "text"},
  {name: "suc_acreditacion", label: "Sucursal Acreditación", placeholder: "no_visible", type: "text"},
  {name: "tipo_acreditacion", label: "Tipo Acreditación", placeholder: "no_visible", type: "text"},
  {name: "cuenta_acreditacion", label: "Cuenta Acreditación", placeholder: "no_visible", type: "text"},
  {name: "cuenta_acreditacion_dv", label: "DV Cuenta Acreditación", placeholder: "no_visible", type: "text"},
  {name: "importe_acreditado", label: "Importe Acreditado", placeholder: "Importe Acreditado", type: "float"},
  {name: "beneficiario_nombre", label: "Beneficiario", placeholder: "Beneficiario", type: "text"},
  {name: "documento_tipo", label: "Tipo Documento", placeholder: "no_visible", type: "text"},
  {name: "documento_nro", label: "Número Documento", placeholder: "no_visible", type: "text"},
  {name: "suc_debito", label: "Sucursal Débito", placeholder: "no_visible", type: "text"},
  {name: "tipo_debito", label: "Tipo Débito", placeholder: "no_visible", type: "text"},
  {name: "cuenta_debito", label: "Cuenta Débito", placeholder: "no_visible", type: "text"},
  {name: "cuenta_debito_dv", label: "DV Cuenta Débito", placeholder: "no_visible", type: "text"},
  {name: "cuil", label: "CUIL", placeholder: "CUIL", type: "text"},
  {name: "zona", label: "Zona", placeholder: "Zona", type: "text"},
  {name: "centro", label: "Centro", placeholder: "Centro", type: "text"},
  {name: "sector", label: "Sector", placeholder: "Sector", type: "text"},
  {name: "padron", label: "Padrón", placeholder: "Padrón", type: "text"},
  {name: "padron_dv", label: "DV Padrón", placeholder: "no_visible", type: "text"},
  {name: "reservado", label: "Reservado", placeholder: "no_visible", type: "text"},
  {name: "cod_banco", label: "Código Banco", placeholder: "no_visible", type: "text"},
  {name: "tipo_archivo", label: "Tipo Archivo", placeholder: "no_visible", type: "text"},
  {name: "periodo", label: "Período", placeholder: "Período", type: "text"},
  {name: "motivo", label: "Motivo", placeholder: "Motivo", type: "select", optionsKey: "motivos"},
  {name: "login", label: "Login", placeholder: "no_visible", type: "text"},
  {name: "empresa", label: "Empresa", placeholder: "no_visible", type: "text"},
  {name: "activo", label: "Activo", placeholder: "no_visible", type: "checkbox"},
];
