export const formularioCampos = [
  {name: "padron", label: "Padron", placeholder: "Padron", type: "text"},
  {name: "beneficiario_nombre", label: "Apellido Nombre", placeholder: "Apellido Nombre", type: "text"},
  {name: "importe_acreditado", label: "Importe Acreditado", placeholder: "Importe Acreditado", type: "text"},
  {name: "cuenta_debito", label: "Cuenta Debito", placeholder: "Cuenta Debito", type: "text"},
  {name: "bloqueo", label: "Bloqueo", placeholder: "Bloqueo", type: "checkbox"},
  {name: "tipo_reg", label: "Tipo Reg", placeholder: "no_visible", type: "text"},
  {name: "codigo_liquidacion", label: "Codigo Liquidacion", placeholder: "no_visible", type: "text"},
  {name: "centro_pago", label: "Centro Pago", placeholder: "no_visible", type: "text"},
  {name: "pago_anio", label: "Pago Anio", placeholder: "no_visible", type: "text"},
  {name: "pago_mes", label: "Pago Mes", placeholder: "no_visible", type: "text"},
  {name: "pago_dia", label: "Pago Dia", placeholder: "no_visible", type: "text"},
  {name: "suc_acreditacion", label: "Suc Acreditacion", placeholder: "no_visible", type: "text"},
  {name: "tipo_acreditacion", label: "Tipo Acreditacion", placeholder: "no_visible", type: "text"},
  {name: "cuenta_acreditacion", label: "Cuenta Acreditacion", placeholder: "no_visible", type: "text"},
  {name: "cuenta_acreditacion_dv", label: "Cuenta Acreditacion DV", placeholder: "no_visible", type: "text"},
  {name: "documento_tipo", label: "Tipo Documento", placeholder: "no_visible", type: "text"},
  {name: "documento_nro", label: "Nro Documento", placeholder: "no_visible", type: "text"},
  {name: "suc_debito", label: "Suc Debito", placeholder: "no_visible", type: "text"},
  {name: "tipo_debito", label: "Tipo Debito", placeholder: "no_visible", type: "text"},
  {name: "cuenta_debito_dv", label: "Cuenta Debito DV", placeholder: "no_visible", type: "text"},
  {name: "cuil", label: "Cuil", placeholder: "Cuil", type: "text"},
  {name: "zona", label: "Zona", placeholder: "Zona", type: "text"},
  {name: "centro", label: "Centro", placeholder: "Centro", type: "text"},
  {name: "sector", label: "Sector", placeholder: "Sector", type: "text"},
  {name: "padron_dv", label: "Padron DV", placeholder: "no_visible", type: "text"},
  {name: "reservado", label: "Reservado", placeholder: "no_visible", type: "text"},
  {name: "cod_banco", label: "Codigo Banco", placeholder: "no_visible", type: "text"},
  {name: "fecha_pago", label: "Fecha Pago", placeholder: "no_visible", type: "text"},
  {name: "fuente", label: "Fuente", placeholder: "no_visible", type: "text"},
  {name: "motivo", label: "Motivo", placeholder: "Motivo", type: "select", optionsKey: "motivos"},
  {name: "login", label: "Login", placeholder: "no_visible", type: "text"},
  {name: "empresa", label: "Empresa", placeholder: "no_visible", type: "text"},
  {name: "activo", label: "Activo", placeholder: "Activo", type: "checkbox"},
];
