export const formularioCampos = [
  {name: "bloqueo", label: "Bloqueo", placeholder: "Bloqueo", type: "checkbox"},
  {name: "tipo_reg", label: "Tipo Reg", placeholder: "Tipo Reg", type: "text"},
  {name: "codigo_liquidacion", label: "Codigo Liquidación", placeholder: "Codigo Liquidación", type: "text"},
  {name: "centro_pago", label: "Centro Pago", placeholder: "Centro Pago", type: "text"},
  {name: "fecha_pago", label: "Fecha Pago", placeholder: "Fecha Pago", type: "date"},
  {name: "sucursal_acreditacion", label: "Suc Acreditacion", placeholder: "Suc Acreditacion", type: "text"},
  {name: "importe_acreditar", label: "Importe Acreditar", placeholder: "Importe Acreditar", type: "float"},
  {name: "ayn", label: "Apellido Nombre", placeholder: "Apellido Nombre", type: "text"},
  {name: "tipoynumdoc", label: "Tipo  y Numero Doc", placeholder: "Tipo  y Numero Doc", type: "text"},
  {name: "sucursal_cuenta_digitodebito", label: "Suc Cuenta Digito Debito", placeholder: "Suc Cuenta Digito Debito", type: "text"},
  {name: "cuil", label: "Cuil", placeholder: "Cuil", type: "text"},
  {name: "zona", label: "Zona", placeholder: "Zona", type: "text"},
  {name: "centro_sector", label: "Centro Sector", placeholder: "Centro Sector", type: "text"},
  {name: "padron_digitoverificador", label: "Padron", placeholder: "Padron", type: "text"},
  {name: "codigo_banco", label: "Codigo Banco", placeholder: "Codigo Banco", type: "text"},
  {name: "motivo", label: "Motivo", placeholder: "Motivo", type: "select", optionsKey: "motivos"},
  {name: "fuente", label: "Fuente", placeholder: "Fuente", type: "text"},
  {name: "login", label: "login", placeholder: "no_visible", type: "text"},
  {name: "empresa", label: "Empresa", placeholder: "no_visible", type: "text"},
  {name: "activo", label: "Activo", placeholder: "Activo", type: "checkbox"},
];
